# Generated by Django 5.1.3 on 2025-06-25 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_delete_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Venta')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='productos.refaccion')),
            ],
        ),
    ]
