# Generated by Django 5.1.3 on 2025-06-26 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_refaccion_proveedor_alter_categoria_id_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventas',
            options={'ordering': ['-fecha_venta'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterField(
            model_name='ventas',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='productos.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='refaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='productos.refaccion', verbose_name='Refacción'),
        ),
    ]
