# Generated by Django 5.1.6 on 2025-08-27 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '__first__'),
        ('ventas', '0002_alter_ventas_options_alter_ventas_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentasServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_servicios', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Venta de Servicio',
                'verbose_name_plural': 'Ventas de Servicios',
                'ordering': ['-fecha_venta'],
            },
        ),
    ]
