# Generated by Django 5.1.6 on 2025-09-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_ventasservicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventasservicios',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='ventasservicios',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='ventasservicios',
            name='estado_pago',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='ventasservicios',
            name='garantia_dias',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='ventasservicios',
            name='mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventasservicios',
            name='refacciones_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventasservicios',
            name='tecnico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ventasservicios',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
