# Generated by Django 5.1.3 on 2025-06-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_ventasservicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasservicios',
            name='observaciones',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
