# Generated by Django 5.1.6 on 2025-09-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_refaccion_marca'),
        ('ventas', '0004_remove_ventasservicios_costo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Devolución')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.TextField(blank=True, max_length=500, null=True)),
                ('fecha_devolucion', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='productos.marca', verbose_name='Marca')),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='productos.refaccion', verbose_name='Refacción')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones', to='ventas.ventas', verbose_name='Venta relacionada')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_devolucion'],
            },
        ),
    ]
