# Generated by Django 5.1.6 on 2025-09-16 09:03

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='newsletter',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_newsletter_email_ci'),
        ),
    ]
