# Generated by Django 5.1.6 on 2025-12-03 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_alter_pedido_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preference_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobado'), ('REC', 'Rechazado'), ('CAN', 'Cancelado'), ('REE', 'Reembolsado')], default='PEN', max_length=3)),
                ('status_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('payment_method_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('mp_data', models.JSONField(blank=True, default=dict)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['preference_id'], name='pagos_pago_prefere_b9a072_idx'), models.Index(fields=['payment_id'], name='pagos_pago_payment_2aa211_idx'), models.Index(fields=['status'], name='pagos_pago_status_e82174_idx')],
            },
        ),
    ]
