# Generated by Django 5.1.6 on 2025-03-26 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('Motor', 'Motor'), ('Minisplit', 'Minisplit'), ('Lavadora', 'Lavadora'), ('Ventilador', 'Ventilador'), ('Secadora', 'Secadora'), ('Refrigerador', 'Refrigerador'), ('Estufa', 'Estufa'), ('Horno', 'Horno'), ('Microondas', 'Microondas'), ('Licuadora', 'Licuadora'), ('Batidora', 'Batidora'), ('Tostador', 'Tostador'), ('Cafetera', 'Cafetera'), ('Plancha', 'Plancha'), ('Aspiradora', 'Aspiradora'), ('Otros', 'Otros')], default='Otros', max_length=50)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
