# Generated by Django 5.1.6 on 2025-08-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_blog_comment_post_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='resume',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Motor', 'Motor'), ('Minisplit', 'Minisplit'), ('Lavadora', 'Lavadora'), ('Ventilador', 'Ventilador'), ('Refrigerador', 'Refrigerador'), ('Estufa', 'Estufa'), ('Microondas', 'Microondas'), ('Licuadora', 'Licuadora'), ('Cafetera', 'Cafetera'), ('Plancha', 'Plancha'), ('Aspiradora', 'Aspiradora'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
    ]
