# Generated by Django 5.1.6 on 2025-08-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Motor', 'Motor'), ('Minisplit', 'Minisplit'), ('Lavadora', 'Lavadora'), ('Ventilador', 'Ventilador'), ('Refrigerador', 'Refrigerador'), ('Estufa', 'Estufa'), ('Microondas', 'Microondas'), ('Licuadora', 'Licuadora'), ('Cafetera', 'Cafetera'), ('Plancha', 'Plancha'), ('Aspiradora', 'Aspiradora'), ('Pulidora', 'Pulidora'), ('Bombas de agua', 'Bombas de agua'), ('Taladro', 'Taladro'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
    ]
