# Generated by Django 5.1.6 on 2025-12-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
