# Generated by Django 5.1.6 on 2025-12-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='address_colony',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='address_references',
            field=models.TextField(blank=True, null=True, verbose_name='Referencias adicionales'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='address_state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle y número'),
        ),
    ]
