# Generated by Django 5.1.6 on 2025-12-30 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_address_city_usuario_address_colony_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la dirección')),
                ('street', models.CharField(max_length=255, verbose_name='Calle y número')),
                ('colony', models.CharField(max_length=255, verbose_name='Colonia')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('references', models.TextField(blank=True, null=True, verbose_name='Referencias adicionales')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Dirección principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
