# Generated by Django 5.1.6 on 2026-01-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_categoria_imagen_marca_logo_proveedor_logo'),
        ('usuarios', '0005_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_favoritos', to='productos.refaccion', verbose_name='Productos favoritos'),
        ),
    ]
