# Generated by Django 5.1.6 on 2026-01-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_categoria_imagen_marca_logo_proveedor_logo'),
        ('usuarios', '0006_usuario_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='usuarios_carrito', to='productos.refaccion', verbose_name='Carrito de compras'),
        ),
    ]
