# Generated by Django 5.1.6 on 2026-01-17 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_categoria_imagen_marca_logo_proveedor_logo'),
        ('usuarios', '0007_usuario_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cart',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='usuarios.cart')),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='productos.refaccion')),
            ],
            options={
                'unique_together': {('cart', 'refaccion')},
            },
        ),
    ]
