# Generated by Django 5.1.6 on 2026-01-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_usuario_cart_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='barrio_privado',
            field=models.BooleanField(default=False, verbose_name='Se encuentra en un barrio privado o centro comercial'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='conserjeria',
            field=models.BooleanField(default=False, verbose_name='Se pueden dejar paquetes en conserjería'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='horario_24hs',
            field=models.BooleanField(default=False, verbose_name='Atención 24 horas'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='horario_apertura',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario de apertura'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='horario_cierre',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario de cierre'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='horarios_adicionales',
            field=models.JSONField(blank=True, default=dict, verbose_name='Horarios adicionales por día'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='nombre_lugar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del lugar'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='tipo_lugar',
            field=models.CharField(blank=True, choices=[('casa', 'Casa'), ('edificio', 'Edificio'), ('abarrotes', 'Abarrotes'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de lugar'),
        ),
    ]
