# Generated by Django 5.1.6 on 2025-09-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('noDeServicio', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('marca', models.CharField(max_length=100)),
                ('aparato', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cliente', models.CharField(max_length=100)),
                ('pagado', models.BooleanField(default=False, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('nota', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Reparado', 'Reparado'), ('Entregado', 'Entregado'), ('Revision', 'Revision'), ('En Bodega', 'En Bodega')], default='Pendiente', max_length=50)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-noDeServicio'],
            },
            
        ),
    ]
