# Generated by Django 5.1.3 on 2025-06-20 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('noDeServicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('marca', models.CharField(max_length=100)),
                ('aparato', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cliente', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completado', 'Reparado'), ('Entregado', 'Entregado'), ('Revision', 'Revision'), ('En Bodega', 'En Bodega')], default='Pendiente', max_length=50)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-noDeServicio'],
            },
        ),
        migrations.CreateModel(
            name='ServicioReparado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_reparacion', models.DateField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reparados', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Servicio Reparado',
                'verbose_name_plural': 'Servicios Reparados',
            },
        ),
    ]
