# Generated by Django 5.1.6 on 2025-09-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        
    ]
