# Generated by Django 5.1.6 on 2025-09-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_add_nota_field'),
    ]

    operations = [
        migrations.AddField(
    model_name='servicio',
    name='nota',
    field=models.JSONField(blank=True, null=True),
),
    ]
