# Generated by Django 5.1.3 on 2025-06-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicioreparado_costo_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicioreparado',
            constraint=models.UniqueConstraint(fields=('servicio',), name='unico_servicio_reparado'),
        ),
    ]
