# Generated by Django 5.1.3 on 2025-06-28 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_refaccion_proveedor_alter_categoria_id_and_more'),
        ('servicios', '0003_servicioreparado_unico_servicio_reparado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='aparato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='productos.refaccion'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='productos.marca'),
        ),
    ]
