# Generated by Django 5.1.3 on 2025-06-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_servicio_aparato_alter_servicio_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='aparato',
            field=models.CharField(max_length=100),
        ),
    ]
