# Generated by Django 5.1.6 on 2025-07-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_servicio_aparato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Reparado', 'Reparado'), ('Entregado', 'Entregado'), ('Revision', 'Revision'), ('En Bodega', 'En Bodega')], default='Pendiente', max_length=50),
        ),
        migrations.DeleteModel(
            name='ServicioReparado',
        ),
    ]
