# Generated by Django 5.1.6 on 2026-02-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numero_seguimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de seguimiento'),
        ),
    ]
