# Generated by Django 5.1.6 on 2025-05-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
