# Generated by Django 5.1.6 on 2025-08-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_refaccion_proveedor_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refaccion',
            name='marca',
            field=models.CharField(max_length=100),
        ),
    ]
