# Generated by Django 5.1.6 on 2025-10-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_refaccion_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
