# Generated by Django 5.1.6 on 2026-02-09 04:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_categoria_imagen_marca_logo_proveedor_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='productos.refaccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_productos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario de Producto',
                'verbose_name_plural': 'Comentarios de Productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='productos_c_created_b90729_idx'), models.Index(fields=['refaccion', '-created_at'], name='productos_c_refacci_8617af_idx')],
                'unique_together': {('refaccion', 'usuario')},
            },
        ),
    ]
