# Generated by Django 5.1.6 on 2026-02-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_comentarioproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='refaccion',
            name='ubicacion_estante',
            field=models.CharField(blank=True, help_text='Numero de estante/anaquel', max_length=50, null=True),
        ),
    ]
