# Generated by Django 5.1.3 on 2025-06-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('noDeServicio', models.IntegerField(primary_key=True, serialize=False)),
                ('aparato', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bodegas',
                'ordering': ['name'],
            },
        ),
    ]
