# Generated by Django 5.1.3 on 2025-06-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='inventario',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
