# Generated by Django 5.1.3 on 2025-06-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_inventario_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
