# Generated by Django 5.1.3 on 2025-06-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='refaccion',
            field=models.CharField(max_length=200),
        ),
    ]
