# Generated by Django 5.1.3 on 2025-06-26 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inventario_refaccion'),
        ('productos', '0003_refaccion_proveedor_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={},
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='refaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.refaccion'),
        ),
    ]
