# Generated by Django 5.1.3 on 2025-06-26 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_inventario_options_alter_inventario_id_and_more'),
        ('productos', '0003_refaccion_proveedor_alter_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.categoria'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='productos.marca'),
        ),
    ]
