# Generated by Django 5.1.6 on 2025-09-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_inventario_categoria_alter_inventario_marca'),
        ('productos', '0004_alter_refaccion_marca'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['refaccion', 'fecha'], name='inventario__refacci_673b15_idx'),
        ),
    ]
