# Generated by Django 5.1.6 on 2026-02-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_inventario_inventario__refacci_673b15_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
